key: bfv_outpost_NjI3ZDQ2YzYtMTJlZi00NjUzLTkzNDItM2E3MjkwNDEwZjFj
cron: 45 4 * * *
monitor:
  xbl:
    platoons:
      - 627d46c6-12ef-4653-9342-3a7290410f1c
    players:
      - Al capone7429
      - Alita2311
      - DP AA 75
      - eartharoid
      - EricCantona8851
      - IOI VAL IOI
      - RogueKV
      - YarikPisi
    rename:
      VonNeves: Hveerfjall
  psn:
    platoons: []
    players: []
    rename: {}
  origin:
    platoons: []
    players: []
    rename: {}